language: node_js
node_js: lts/*
os:
  - osx
  - linux
env:
  - NODE_ENV=test
install:
  - brew install redis
  - npm install
script:
  - brew services start redis
  - npm test
  - brew services stop redis
