language: node_js
node_js: lts/*
os:
- linux
env:
- NODE_ENV=test
install:
- rm -rf public src package.json package-lock.json
services:
- redis-server
jobs:
  include:
  - stage: Deploy
    script:
    - "./scripts/build.sh"
    deploy:
      provider: heroku
      api_key:
        secure: VmGpzWwqSJbvsjqM0QLVIqxbW637ZHSre91qTcJA52H28mIPicJz3YycKNDXUiC5kH41OF+x3hY+uXOlpTvi9qNgxOO5qHOJnTviy1jkCH3jJ+iTi81lwEPoJnNIV+Cq1PeA1APM4QhD7Y83HmCa+sUzBjSzc68DjcJkkx5VTW7/krv7uCpKa+mFn0Ipi9nrXwQxLNRuyNmwpAADa6Xuuz7QTpQsawLRjfIKyC9ITZh+WxV3hyVAht7P9CF+0ByL9rlwY45A7zQ/H+dOD0l4By395+JjLqja5pxwOPRL5CW5sMLFU74e7bQAqtqfJ0cOnU5NsTdOAd+gWIHZfGxA3WA/lVBbv2adEyD+oGsbSq2vVFrse7x/BlXpRu+jdlcBVC7tFYmyFrhdSIZSEK8FGsNwEwdsT3Pdj771eNsqQ1V+km2ld6LsCI+1tP/5vosl+YgMqJ2Sl1JzzvqKLfSasBu/PC+FB21cy0bRkXvQGuuCSvPKoYKuIYh3vMmlKFQALXf6F6f9OzYtNCp89ZUO+kORHczN5YxjFbZP4WKkXx2tDpdIR4R/ZjKKdf1DI9O8WERWQhwC+frNlAZ/FRPow0fk4i6MBBSTI8G/7xVogj4715frHRq2k0gZxpW95biI8eF4CXtRBY+I2JwUvU9a5sHdqC5zPzd0w8UR+GPX5Qo=
      skip_cleanup: true
      app: sukhiboi-blog
      run: restart
