name: Heroku Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'sukhiboi-blog'
          heroku_email: '41sukhdevsingh@gmail.com'
      - name: Build react and backend
        run: ./scripts/build.sh
